In [2]:
import numpy as np

In [3]:
# En esta lección hemos aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. 
# Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.  

In [4]:
# Ejercicio 1
# Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [5]:
array3d = np.random.random_sample((2,3,5)).round(1)

In [6]:
array3d

array([[[0.4, 0.8, 0.5, 0.7, 0.2],
        [0.3, 0.2, 0.8, 0.3, 0.2],
        [0.2, 0. , 0.1, 0.8, 0.6]],

       [[0.2, 0.4, 0.4, 0.5, 1. ],
        [0.8, 0.9, 0.5, 0.1, 0.9],
        [0.4, 0.1, 0.3, 0.3, 0.5]]])

In [7]:
# Ejercicio 2
# Calculad la media del array y almacenarlos en una variable. Redondead a un decimal

In [8]:
media = np.mean(array3d).round(1)
media

0.4

In [9]:
# Ejercicio 3
# Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [10]:
maxi = np.max(array3d).round(1)
maxi

1.0

In [11]:
# Ejercicio 4 
# Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [12]:
mini = np.min(array3d)
mini

0.0

In [13]:
# Ejercicio 5
# Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente
# Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
#Si el valor del array es igual que la media, se reemplaza por "A".
#Si el valor del array es mayor que la media, se reemplaza por "B".
#Si el valor del array es menor que la media, se reemplaza por "C".
#Si el valor es igual que el máximo, se reemplaza por "D"

In [14]:
array3d_vacio = np.empty_like(array3d, dtype = str )
array3d_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [15]:
# para ir encontrando los indices generamos un contador. (3 contadores, en este caso) 
# Le aplicamos las condiciones al elemento elegido y cuando cumpla una, pasamos el contador para ir al siguiente elemento y "guardar" su posición

c1 = 0
c2 = 0
c3 = 0

for dim1 in array3d:
   for dim2 in dim1:
    for dim3 in dim2:
        if dim3 == maxi:
            array3d_vacio[c1][c2][c3] = "D"
        elif dim3 == media:
            array3d_vacio[c1][c2][c3] = "A"
        elif dim3 > media:
            array3d_vacio[c1][c2][c3] = "B"
        elif dim3 < media:
            array3d_vacio[c1][c2][c3] = "C"
        

        c3 += 1
        if c3 > 4:
            c3 = 0
            c2 += 1
            if c2 > 2:
                c2 = 0
                c1 += 1
                if c1 > 1:
                    break
    

In [16]:
array3d_vacio

array([[['A', 'B', 'B', 'B', 'C'],
        ['C', 'C', 'B', 'C', 'C'],
        ['C', 'C', 'C', 'B', 'B']],

       [['C', 'A', 'A', 'B', 'D'],
        ['B', 'B', 'B', 'C', 'B'],
        ['A', 'C', 'C', 'C', 'B']]], dtype='<U1')

In [17]:

# DUDA PARA LA REVISIÓN

# En mi array tipo string no me permite meter un string de más de len 1. ¿Qué pasa?

array3d_vacio[0][0][0] = "no entiendo nada"
array3d_vacio[0][0][0]


'n'

In [18]:

# teniamos una ayuda de codigo, que nos definía rangos para identificar los índices. Asi que hemos desarrollado las dos formas. 

for x in range(0,2):
    
    for y in range (0,3):
        
        for z in range(0,5):
            
            
            if array3d[x][y][z] == maxi:
                array3d_vacio[x][y][z] = "D"
            elif array3d[x][y][z] == media:
                array3d_vacio[x][y][z]= "A"
            elif array3d[x][y][z] > media:
                array3d_vacio[x][y][z]= "B"
            elif array3d[x][y][z] < media:
                array3d_vacio[x][y][z]= "C"


In [19]:
array3d_vacio

array([[['A', 'B', 'B', 'B', 'C'],
        ['C', 'C', 'B', 'C', 'C'],
        ['C', 'C', 'C', 'B', 'B']],

       [['C', 'A', 'A', 'B', 'D'],
        ['B', 'B', 'B', 'C', 'B'],
        ['A', 'C', 'C', 'C', 'B']]], dtype='<U1')

In [20]:
# Ejercicio 6
# Estupendo, tenemos un array con strings. 
# Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional 
# de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones 
# con la misma forma que el primero que nos creamos.
# Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
# Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
# Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
# Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [21]:
arr = np.empty(30, dtype = int)
arr

array([4600877379321698714, 4605380978949069210, 4602678819172646912,
       4604480259023595110, 4596373779694328218, 4599075939470750515,
       4596373779694328218, 4605380978949069210, 4599075939470750515,
       4596373779694328218, 4596373779694328218,                   0,
       4591870180066957722, 4605380978949069210, 4603579539098121011,
       4596373779694328218, 4600877379321698714, 4600877379321698714,
       4602678819172646912, 4607182418800017408, 4605380978949069210,
       4606281698874543309, 4602678819172646912, 4591870180066957722,
       4606281698874543309, 4600877379321698714, 4591870180066957722,
       4599075939470750515, 4599075939470750515, 4602678819172646912])

In [22]:
# aquí parece mejor opción usar un contador para ir relacionando las posiciones por indices del array de varias dimensiones, 
# con la posición por índices del array de una sola dimensión

contador = 0

for x in range(0,2):
    
    for y in range (0,3):
        
        for z in range(0,5):

            if array3d_vacio[x][y][z] =="D" or array3d_vacio[x][y][z] == "C":
                arr[contador] = 2
            elif array3d_vacio[x][y][z] == "A" or array3d_vacio[x][y][z] == "B":
                arr[contador] = 1
            else:
                arr[contador] = 3 # el enunciado se refiere a "E", pero no existe previamente.
            contador += 1

            if contador > 29:
                break



In [23]:
array3d_vacio

array([[['A', 'B', 'B', 'B', 'C'],
        ['C', 'C', 'B', 'C', 'C'],
        ['C', 'C', 'C', 'B', 'B']],

       [['C', 'A', 'A', 'B', 'D'],
        ['B', 'B', 'B', 'C', 'B'],
        ['A', 'C', 'C', 'C', 'B']]], dtype='<U1')

In [24]:
arr

array([1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1,
       1, 2, 1, 1, 2, 2, 2, 1])

In [25]:
arr2 = arr.reshape(2,3,5)
arr2

array([[[1, 1, 1, 1, 2],
        [2, 2, 1, 2, 2],
        [2, 2, 2, 1, 1]],

       [[2, 1, 1, 1, 2],
        [1, 1, 1, 2, 1],
        [1, 2, 2, 2, 1]]])