In [1]:
import numpy as np

In [2]:
# Ejercicio 1

# Cread tres arrays: de una, dos y tres dimensiones.

# Array 1 dimensión

lista1 = [1,2,3,4,5,6]

array1 = np.array(lista1)

array1

array([1, 2, 3, 4, 5, 6])

In [3]:
# Array 2 dimensiones

array2 = np.random.randint(0,100, (2,3))
array2

array([[ 9, 48, 30],
       [61,  9,  1]])

In [4]:
# Array 3 dimensiones

array3 = np.random.rand(2,3,5)
array3

array([[[0.48048706, 0.14864722, 0.29263338, 0.19122859, 0.2582837 ],
        [0.47929023, 0.43808711, 0.38249811, 0.38834075, 0.39736627],
        [0.74912706, 0.37292679, 0.71769791, 0.74736454, 0.49064752]],

       [[0.31680709, 0.33220673, 0.79278275, 0.9152476 , 0.67116356],
        [0.8757216 , 0.5348809 , 0.49020838, 0.07922618, 0.88368927],
        [0.96198536, 0.6663884 , 0.28394007, 0.54770346, 0.46817287]]])

In [6]:
# Ejercicio 2

def definir_propiedades(array):
    shape = array.shape
    size = array.size
    dim = array.ndim
    type = array.dtype
    print(f"La forma de tu array es {shape}.")
    print(f"El número total de elemnentos de tu array es {size}.")
    print(f"Es un array de {dim} dimensiones.")
    print(f"Los datos de tu array son de tipo {type}.")

In [7]:
definir_propiedades(array2)

La forma de tu array es (2, 3).
El número total de elemnentos de tu array es 6.
Es un array de 2 dimensiones.
Los datos de tu array son de tipo int64.


In [8]:
definir_propiedades(array1)

La forma de tu array es (6,).
El número total de elemnentos de tu array es 6.
Es un array de 1 dimensiones.
Los datos de tu array son de tipo int64.


In [9]:
definir_propiedades(array3)

La forma de tu array es (2, 3, 5).
El número total de elemnentos de tu array es 30.
Es un array de 3 dimensiones.
Los datos de tu array son de tipo float64.


In [12]:
# Ejercicio 3. Cread una matriz identidad de dos dim de tres filas y tres columnas
identidad = np.identity(3)
identidad


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
#Hacemos pruebas con una matriz rectangular

identidad2 = np.eye(3,2, k=-1)
print(identidad2)

[[0. 0.]
 [1. 0.]
 [0. 1.]]


In [ ]:
# Ejercicio 4. Matriz de 3 dimensiones de 1 creadas igual que la anterior

In [13]:
identidad3 = np.ones_like(identidad)
print(identidad3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# Ejercicio 5. 

# ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué
# 
# No podemos sumar array2 (3x2) con identidad3 (3x3) porque no tienen las misma forma

# En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

print(array2)
print(identidad3)

[[62 73 89]
 [30 32  2]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
#Tenemos que cambiar la forma de una de las dos matrices para poderlas sumar

identidad_suma = np.ones_like(array2)
print(identidad_suma)

[[1 1 1]
 [1 1 1]]


In [31]:
# Procedemos a sumarlas con el operador suma +

array2 + identidad_suma

array([[63, 74, 90],
       [31, 33,  3]])

In [32]:
# Podemos usar el método np.add() para sumar arrays
np.add(array2, identidad_suma)

array([[63, 74, 90],
       [31, 33,  3]])

In [14]:
# Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

# identidad_suma es una matriz de 2x3 e identidad3 es una matriz de 3x3

# No podemos multiplicar esas dos matrices porque no tienen la misma forma. Probamos entonces con dos matrices de idéntica forma (3*3)


In [17]:
# Podemos usar el operador de multiplicar matrices de numpy *

identidad * identidad3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# Podemos usar el método np.multiply()
np.multiply(identidad, identidad3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Dividid las dos matricess

identidad / identidad3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Usando el metodo np.divide()
np.divide(identidad, identidad3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Probamos a crear una matriz de dos dimensiones de otro modo, definiendo a mano el array

In [46]:
matriz1 = np.array([[2,3],[4,5]])
matriz1

array([[2, 3],
       [4, 5]])

In [47]:
np.ndim(matriz1)

2

In [48]:
# Queremos comprobar las diferencias entre la operación de multiplicar matrices de numpy
#  y la operación clásica de producto de matrices algebraica, que se realiza con el método np.dot
matriz1 * matriz1

array([[ 4,  9],
       [16, 25]])

In [49]:
np.dot(matriz1, matriz1)

array([[16, 21],
       [28, 37]])

In [ ]:
# La operación multiplicación multiplica elemento a elemento siguiendo los índices de las matrices, por eso es necesario que tengan la misma forma.
# El producto matricial que se consigue con np.dot tiene que seguir las normas del producto matricial y no tiene porqué tener la misma forma, si cumple las condiciones. 