In [1]:
import numpy as np

In [8]:
# Ejercicio 1
array1 = np.random.randint(0,50,(5,3))

In [9]:
array1

array([[12, 30, 28],
       [40,  7,  1],
       [47, 41, 17],
       [ 5, 22,  0],
       [42, 41, 17]])

In [10]:
array1[0,1]

30

In [11]:
array1[1,:2]

array([40,  7])

In [12]:
array1[::2,]

array([[12, 30, 28],
       [47, 41, 17],
       [42, 41, 17]])

In [13]:
# puedes hacerlo de esta forma(sin indicar la coma que separa filas y columnas) y el resultado será el mismo
array1[::2]

array([[12, 30, 28],
       [47, 41, 17],
       [42, 41, 17]])

In [17]:
array1[array1 > 0.5]

array([12, 30, 28, 40,  7,  1, 47, 41, 17,  5, 22, 42, 41, 17])

In [22]:
# ojo! las condiciones tienen que ir entre parentesis

array1[(array1 < 0.2 )|(array1 > 0.5)]

array([30, 28, 40,  1, 47, 41, 22,  0, 42, 41])

In [ ]:
array1[(array1 < 3)|(array1 > 20)]

In [23]:
# Ejercicio 2

array2 = np.random.randint(0,50,(2,5,3))
array3 = np.random.randint(0,50,(3,2,5))

In [26]:
def definir_propiedades(array):
    shape = array.shape
    size = array.size
    dim = array.ndim
    type = array.dtype
    print(f"La forma de tu array es {shape}")
    print(f"El tamaño de tu array es {size}")
    print(f"El número de dimensiones de tu array es {dim}")
    print(f"El tipo de datos de tu array es {type}")

In [27]:
definir_propiedades(array2)


La forma de tu array es (2, 5, 3)
El tamaño de tu array es 30
El número de dimensiones de tu array es 3
El tipo de datos de tu array es int64


In [28]:
definir_propiedades(array3)

La forma de tu array es (3, 2, 5)
El tamaño de tu array es 30
El número de dimensiones de tu array es 3
El tipo de datos de tu array es int64


In [29]:
# Creemos que no nos va a dejar porque la forma es diferente. Solo podemos sumar arrays con formas iguales.
suma = array2 + array3

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

In [41]:
array2

array([[[47, 15, 20],
        [27, 28, 20],
        [ 0, 13, 43],
        [14, 35, 40],
        [15, 37, 22]],

       [[21, 42,  5],
        [ 1, 10, 28],
        [13, 48, 30],
        [32, 24, 34],
        [10, 42, 38]]])

In [43]:
# hemos cambiado el número de arrays por el número de filas, el número de filas por el número de columnas y el número de columnas por el número de arrays. 
array2_con_transpose = np.transpose(array2,(2,0,1))
array2_con_transpose

array([[[47, 27,  0, 14, 15],
        [21,  1, 13, 32, 10]],

       [[15, 28, 13, 35, 37],
        [42, 10, 48, 24, 42]],

       [[20, 20, 43, 40, 22],
        [ 5, 28, 30, 34, 38]]])

In [ ]:
suma =  array2_con_transpose + array3
suma

In [42]:
array2

array([[[47, 15, 20],
        [27, 28, 20],
        [ 0, 13, 43],
        [14, 35, 40],
        [15, 37, 22]],

       [[21, 42,  5],
        [ 1, 10, 28],
        [13, 48, 30],
        [32, 24, 34],
        [10, 42, 38]]])

In [40]:
# coge de uno en uno los elementos del array y los ubica dentro de la "nueva forma" que le hemos definido. Lo hace de modo "literal" sin seguir una lógica de ejes.
array2_con_reshape = np.reshape(array2,(3,2,5))
array2_con_reshape

array([[[47, 15, 20, 27, 28],
        [20,  0, 13, 43, 14]],

       [[35, 40, 15, 37, 22],
        [21, 42,  5,  1, 10]],

       [[28, 13, 48, 30, 32],
        [24, 34, 10, 42, 38]]])

In [ ]:
suma_reshape = array2_con_reshape + array3
suma_reshape