In [1]:
import numpy as np

In [2]:
# Ejercicio 1
# Crea un array y vamos a aplicarle filtros para extraer distintos datos.
array1 = np.random.randint(0,50,(5,3))

In [3]:
array1

array([[26,  6, 22],
       [48, 22, 39],
       [22, 34, 22],
       [19, 16, 13],
       [18, 12, 27]])

In [4]:
# Valor de la primera fila, segunda columna
array1[0,1]

6

In [5]:
# Valores de la segunda fila y las dos primeras columnas
array1[1,:2]

array([48, 22])

In [6]:
# Filas pares y todas las columnas
array1[::2,]

array([[26,  6, 22],
       [22, 34, 22],
       [18, 12, 27]])

In [7]:
# Filas pares y todas las columnas
# puedes hacerlo de esta forma(sin indicar la coma que separa filas y columnas) y el resultado será el mismo
array1[::2]

array([[26,  6, 22],
       [22, 34, 22],
       [18, 12, 27]])

In [8]:
# Todos los valores mayores que 0.5 (ojo! los decimales se defines con punto, no con coma!)
array1[array1 > 0.5]

array([26,  6, 22, 48, 22, 39, 22, 34, 22, 19, 16, 13, 18, 12, 27])

In [9]:
# Todos los valores menores que 0.2 o mayores que 0.5
# ojo! las condiciones tienen que ir entre parentesis

array1[(array1 < 0.2 )|(array1 > 0.5)]

array([26,  6, 22, 48, 22, 39, 22, 34, 22, 19, 16, 13, 18, 12, 27])

In [10]:
# Como nuestro array tiene numeros enteros mayores que 1, probamos esta otra: 
# Todos los valores menores que 3 o mayores que 20
array1[(array1 < 3)|(array1 > 20)]

array([26, 22, 48, 22, 39, 22, 34, 22, 27])

In [11]:
# Ejercicio 2

# Crea dos arrays de 3 dimensiones (1. 2 matrices, 5 filas y 3 columnas, 2. 3 matrices, 2 filas y 5 columnas)

array2 = np.random.randint(0,50,(2,5,3))
array3 = np.random.randint(0,50,(3,2,5))

In [12]:
# queremos analizar estos arrays, lo hacemos usando una función ya definida en el anterior ejercicio.

def definir_propiedades(array):
    shape = array.shape
    size = array.size
    dim = array.ndim
    type = array.dtype
    print(f"La forma de tu array es {shape}.")
    print(f"El número total de elemnentos de tu array es {size}.")
    print(f"Es un array de {dim} dimensiones.")
    print(f"Los datos de tu array son de tipo {type}.")

In [13]:
definir_propiedades(array2)


La forma de tu array es (2, 5, 3).
El número total de elemnentos de tu array es 30.
Es un array de 3 dimensiones.
Los datos de tu array son de tipo int64.


In [14]:
definir_propiedades(array3)

La forma de tu array es (3, 2, 5).
El número total de elemnentos de tu array es 30.
Es un array de 3 dimensiones.
Los datos de tu array son de tipo int64.


In [15]:
# La forma de los arrays es diferente, aunque el resto de propiedades coinciden. 
# nos piden que los sumemos. Creemos que no nos va a dejar porque la forma es diferente. Solo podemos sumar arrays con formas iguales.
suma = array2 + array3

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

In [16]:
# Vamos a cambiarle la forma a uno de nuestros arrays para poder operar entre ellos. 
array2

array([[[36, 39,  2],
        [15, 24, 22],
        [45, 10, 30],
        [16, 32, 39],
        [41,  5, 11]],

       [[ 5,  3,  2],
        [44, 33, 47],
        [48, 21,  7],
        [49, 37,  3],
        [ 9,  3, 34]]])

In [17]:
# METODO .transpose() : hemos cambiado el número de arrays por el número de filas, el número de filas por el número de columnas y el número de columnas por el número de arrays. 
array2_con_transpose = np.transpose(array2,(2,0,1))
array2_con_transpose

array([[[36, 15, 45, 16, 41],
        [ 5, 44, 48, 49,  9]],

       [[39, 24, 10, 32,  5],
        [ 3, 33, 21, 37,  3]],

       [[ 2, 22, 30, 39, 11],
        [ 2, 47,  7,  3, 34]]])

In [18]:
suma =  array2_con_transpose + array3
suma

array([[[46, 55, 46, 39, 73],
        [22, 46, 65, 93, 47]],

       [[79, 51, 17, 74,  8],
        [ 8, 56, 58, 53, 42]],

       [[36, 34, 79, 85, 20],
        [50, 65, 37, 15, 43]]])

In [19]:
array2

array([[[36, 39,  2],
        [15, 24, 22],
        [45, 10, 30],
        [16, 32, 39],
        [41,  5, 11]],

       [[ 5,  3,  2],
        [44, 33, 47],
        [48, 21,  7],
        [49, 37,  3],
        [ 9,  3, 34]]])

In [20]:
# METODO .reshape() : coge de uno en uno los elementos del array y los ubica dentro de la "nueva forma" que le hemos definido. Lo hace de modo "literal" sin seguir una lógica de ejes.
array2_con_reshape = np.reshape(array2,(3,2,5))
array2_con_reshape

array([[[36, 39,  2, 15, 24],
        [22, 45, 10, 30, 16]],

       [[32, 39, 41,  5, 11],
        [ 5,  3,  2, 44, 33]],

       [[47, 48, 21,  7, 49],
        [37,  3,  9,  3, 34]]])

In [21]:
suma_reshape = array2_con_reshape + array3
suma_reshape

array([[[46, 79,  3, 38, 56],
        [39, 47, 27, 74, 54]],

       [[72, 66, 48, 47, 14],
        [10, 26, 39, 60, 72]],

       [[81, 60, 70, 53, 58],
        [85, 21, 39, 15, 43]]])

In [ ]:
# Al aplicar distintos métodos para "reformar" el array, nos devuelve dsitintos resultados de suma. A tener en cuenta. 