In [2]:
import numpy as np

In [1]:
# En esta lección hemos aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. 
# Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.  

In [ ]:
# Ejercicio 1
# Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [10]:
array3d = np.random.random_sample((2,3,5)).round(1)

In [27]:
array3d

array([[[0.2, 0.9, 0.6, 0.8, 0.2],
        [0.1, 0.9, 0.1, 0.1, 0.8],
        [0. , 0.9, 0.8, 0.6, 0.5]],

       [[0.8, 0.4, 1. , 0.2, 0.2],
        [0.7, 0.4, 0.1, 0.2, 1. ],
        [0.7, 0.6, 0.7, 0.5, 0.5]]])

In [28]:
# Ejercicio 2
# Calculad la media del array y almacenarlos en una variable. Redondead a un decimal

In [69]:
media = np.mean(array3d).round(1)
media

0.5

In [30]:
# Ejercicio 3
# Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [31]:
max = np.max(array3d).round(1)
max

1.0

In [ ]:
# Ejercicio 4 
# Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [32]:
min = np.min(array3d)
min

0.0

In [ ]:
# Ejercicio 5
# Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente
# Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
#Si el valor del array es igual que la media, se reemplaza por "A".
#Si el valor del array es mayor que la media, se reemplaza por "B".
#Si el valor del array es menor que la media, se reemplaza por "C".
#Si el valor es igual que el máximo, se reemplaza por "D"

In [110]:
array3d_vacio = np.empty_like(array3d, dtype = str )
array3d_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [108]:
array3d_vacio.dtype

dtype('<U1')

In [111]:
array3d_vacio.shape

(2, 3, 5)

In [112]:
for x in range(0,2):
    print(x)
    for y in range (0,3):
        print(y)
        for z in range(0,5):
            print(z)

0
0
0
1
2
3
4
1
0
1
2
3
4
2
0
1
2
3
4
1
0
0
1
2
3
4
1
0
1
2
3
4
2
0
1
2
3
4


In [113]:
array3d_vacio[x][y][z]

''

In [92]:
for a in array3d_vacio:
        for b in a:
                for c in b:
                        if c > media:
                                print(f'{c} es mayor que {media}')
                                c = "A"
                                print(c)
                                
                                                       
    
    

0.9 es mayor que 0.5
A
0.6 es mayor que 0.5
A
0.8 es mayor que 0.5
A
0.9 es mayor que 0.5
A
0.8 es mayor que 0.5
A
0.9 es mayor que 0.5
A
0.8 es mayor que 0.5
A
0.6 es mayor que 0.5
A
0.8 es mayor que 0.5
A
1.0 es mayor que 0.5
A
0.7 es mayor que 0.5
A
1.0 es mayor que 0.5
A
0.7 es mayor que 0.5
A
0.6 es mayor que 0.5
A
0.7 es mayor que 0.5
A


In [36]:
np.any(array3d_vacio > media)

True

In [37]:
np.where(array3d_vacio > media)

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]),
 array([0, 0, 0, 1, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2, 2]),
 array([1, 2, 3, 1, 4, 1, 2, 3, 0, 2, 0, 4, 0, 1, 2]))