In [2]:
import numpy as np

In [4]:
# Ejercicio 1

# Cread tres arrays: de una, dos y tres dimensiones.

# Array 1 dimensión

lista1 = [1,2,3,4,5,6]

array1 = np.array(lista1)

array1

array([1, 2, 3, 4, 5, 6])

In [5]:
# Array 2 dimensiones

array2 = np.random.randint(0,100, (2,3))
array2

array([[62, 73, 89],
       [30, 32,  2]])

In [8]:
# Array 3 dimensiones

array3 = np.random.rand(2,3,5)
array3

array([[[0.83172795, 0.30786447, 0.26029305, 0.44121004, 0.36647193],
        [0.56466332, 0.91770502, 0.63128225, 0.35153774, 0.81094377],
        [0.21399792, 0.6445257 , 0.33582893, 0.01306374, 0.22760676]],

       [[0.2707075 , 0.15779559, 0.00719734, 0.65059013, 0.14510804],
        [0.37832105, 0.85638399, 0.63660268, 0.65021429, 0.60761034],
        [0.90287954, 0.94649396, 0.41494396, 0.17606516, 0.48582909]]])

In [14]:
# Ejercicio 2

def definir_propiedades(array):
    shape = array.shape
    size = array.size
    dim = array.ndim
    type = array.dtype
    print(shape)
    print(size)
    print(dim)
    print(type)

In [15]:
definir_propiedades(array2)

(2, 3)
6
2
int64


In [16]:
definir_propiedades(array1)

(6,)
6
1
int64


In [17]:
definir_propiedades(array3)

(2, 3, 5)
30
3
float64


In [26]:
# Ejercicio 3. Cread una matriz identidad de dos dim de tres filas y tres columnas
identidad = np.identity(3)
identidad


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#Hacemos pruebas con una matriz rectangular

identidad2 = np.eye(3,2, k=-1)
print(identidad2)

[[0. 0.]
 [1. 0.]
 [0. 1.]]


In [ ]:
# Ejercicio 4. Matriz de 3 dimensiones de 1 creadas igual que la anterior

In [27]:
identidad3 = np.ones_like(identidad)
print(identidad3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# Ejercicio 5. 

# ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué
# 
# No podemos sumar array2 (3x2) con identidad3 (3x3) porque no tienen las misma forma

# En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

print(array2)
print(identidad3)

[[62 73 89]
 [30 32  2]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
#Tenemos que cambiar la forma de una de las dos matrices para poderlas sumar

identidad_suma = np.ones_like(array2)
print(identidad_suma)

[[1 1 1]
 [1 1 1]]


In [31]:
# Procedemos a sumarlas

array2 + identidad_suma

array([[63, 74, 90],
       [31, 33,  3]])

In [32]:
np.add(array2, identidad_suma)

array([[63, 74, 90],
       [31, 33,  3]])

In [36]:
# Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

# identidad_suma es una matriz de 2x3 e identidad3 es una matriz de 3x3

# No podemos multiplicar esas dos matrices porque no tienen la misma forma. Probamos entonces con dos matrices de idéntica forma (3*3)

identidad3 * identidad3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
# Dividid las dos matricess

identidad3 / identidad3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
matriz1 = np.array([[2,3],[4,5]])
matriz1

array([[2, 3],
       [4, 5]])

In [50]:
matriz1

array([[2, 3],
       [4, 5]])

In [47]:
np.ndim(matriz1)

2

In [48]:
matriz1 * matriz1

array([[ 4,  9],
       [16, 25]])

In [49]:
np.dot(matriz1, matriz1)

array([[16, 21],
       [28, 37]])