In [1]:
import pandas as pd
import numpy as np

# Ejercicio 1

Diferencia entre Serie y Dataframe. Se diferencia en el número de dimernsiones, una serie es un objeto unidimensional y el DataFrame es bidimensional (2 dimensiones)


In [1]:
# Ejercicio 2

valores = [2, 5, 7, 4, 8, 10, 22]
indices = ["Lunes","Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"]


In [4]:
serie1 = pd.Series(valores, index= indices)
print(serie1)

In [40]:
for a in (valores, indices):
    dict_from_list = dict(zip(indices, valores))
print(dict_from_list)
    



{'Lunes': 2, 'Martes': 5, 'Miercoles': 7, 'Jueves': 4, 'Viernes': 8, 'Sabado': 10, 'Domingo': 22}


In [41]:
serie2 = pd.Series(dict_from_list)
print(serie2)

Lunes         2
Martes        5
Miercoles     7
Jueves        4
Viernes       8
Sabado       10
Domingo      22
dtype: int64


In [42]:
serie2.shape

(7,)

In [43]:
serie2.dtypes

# Puede que nos lo devuelva vacío porque son distitnos tips de datos en la misma serie????

dtype('int64')

In [44]:
serie2.size

7

In [45]:
serie2.index

Index(['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado',
       'Domingo'],
      dtype='object')

In [46]:
serie2.values

array([ 2,  5,  7,  4,  8, 10, 22])

In [47]:
serie2["Lunes"]

2

In [48]:
serie2[:"Miercoles"]

Lunes        2
Martes       5
Miercoles    7
dtype: int64

In [55]:
serie2[:7:6]

Lunes       2
Domingo    22
dtype: int64

In [60]:
# Ejercicio 3


array1 = np.array([[2,4,5], [5,6,3], [7,6,5], [9,9,8]])

print(array1)

[[2 4 5]
 [5 6 3]
 [7 6 5]
 [9 9 8]]


In [65]:
df1 = pd.DataFrame(array1, columns = ["España", "Francia", "Italia"])
df1

España  Francia  Italia
0       2        4       5
1       5        6       3
2       7        6       5
3       9        9       8

In [9]:
df = pd.read_csv("medallas.csv", index_col=["País"])
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [68]:
df.loc["China"]

Unnamed: 0       1
Oro           1473
Plata          994
Bronce         720
Name: China, dtype: int64

In [74]:
df.loc["China":"Irán":3]


Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

In [75]:
df.loc[["China", "Irán"]]

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

In [76]:
df.loc[["China", "Irán"],["Oro","Plata","Bronce"]]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

In [79]:
df.iloc[5]

# ¿Cómo podemos obtener el indice de India sin tener que contar la posición en la que aparece en el dataframe?

Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64

In [86]:
df.iloc[1::2]

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

In [63]:
#Que pais consiguió más medallas de 200 medallas de oro?

df.loc[(df.Oro > 200)].head(1)

Unnamed: 0   Oro  Plata  Bronce  Total
País                                         
China           1  1473    994     720   3187

In [69]:
df.loc[(df.Oro > 200)].iloc[0]

Unnamed: 0       1
Oro           1473
Plata          994
Bronce         720
Total         3187
Name: China, dtype: int64

In [23]:
#Que pais consiguió más medallas de 200 medallas de oro y 100 de plata?

df.loc[(df.Oro > 200) & (df.Plata > 1000)]

Unnamed: 0   Oro  Plata  Bronce
País                                  
Japón           2  1032   1037     985

In [24]:
#Que pais consiguió más medallas de 200 medallas de oro o 700 de bronce?

df.loc[(df.Oro > 200) | (df.Plata > 1000)]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [26]:
# Eliminar columna unnamed

# Hacemos copia de seguridad del df porsiaca

df2 = df.copy()

In [56]:
df2

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [59]:
del df2["Unnamed: 0"]

In [60]:
df2

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

In [61]:
# Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

df2["Total"] = (df["Oro"] + df["Plata"] + df["Bronce"])

In [62]:
df2

Oro  Plata  Bronce  Total
País                                       
China            1473    994     720   3187
Japón            1032   1037     985   3054
Corea del Sur     745    663     827   2235
Irán              179    181     197    557
Kazajistán        155    158     224    537
India             154    202     315    671
Tailandia         132    175     278    585
Indonesia         112    131     240    483
China Taipéi       99    144     276    519
Corea del Norte    91    120     235    446