In [1]:
import numpy as np

In [2]:
# Ejercicio: 1
# ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

# Utilizando la semilla

np.random.seed(42)

array1 = np.round(np.random.random_sample((2,3)),2)
array1



array([[0.37, 0.95, 0.73],
       [0.6 , 0.16, 0.16]])

In [3]:
array2 = np.round(np.random.random_sample((2,3)),2)
array2

array([[0.06, 0.87, 0.6 ],
       [0.71, 0.02, 0.97]])

In [ ]:
# Ejercicio: 2
# Cread los siguientes arrays:
# Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable
# Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.

In [4]:
array_uni = np.round(np.random.uniform(0,10,(2,3,5)),0)
array_uni

array([[[ 8.,  2.,  2.,  2.,  3.],
        [ 5.,  4.,  3.,  6.,  1.],
        [ 3.,  4.,  5.,  8.,  2.]],

       [[ 5.,  6.,  0.,  6.,  2.],
        [ 1.,  9., 10.,  8.,  3.],
        [ 1.,  7.,  4.,  1.,  5.]]])

In [5]:
valores_unicos_uni= np.unique(array_uni)
valores_unicos_uni

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
array_bin = np.random.binomial(10, 0.3, size = (2,3,5))
array_bin

array([[[1, 5, 2, 4, 2],
        [3, 3, 2, 6, 4],
        [5, 5, 3, 5, 1]],

       [[2, 1, 2, 3, 2],
        [4, 2, 2, 3, 1],
        [4, 1, 6, 4, 2]]])

In [7]:
valores_unicos_bin = np.unique(array_bin)
valores_unicos_bin

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Ejercicio 3
# En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior 
# realizad las siguientes operaciones:

In [26]:
# Elementos comunes entre los dos arrays

np.intersect1d(valores_unicos_uni, valores_unicos_bin)

# Estamos extrayendo los valores comunes a los dos arrays, la intersección de ambos. Aparecen ordenados de menor a mayor.

array([0., 1., 2., 3., 4., 5.])

In [27]:
# Unión de los dos arrays

np.union1d(valores_unicos_uni, valores_unicos_bin)

# Estamos extrayendo los valores únicos que están en los dos arrays (sin repetidos). Aparecen ordenados de menor a mayor.

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [28]:
np.setdiff1d(array_uni, array_bin)

# Estamos obteniendo los valores únicos que están en el primer array(uniforme) y no están en el segundo(binomial)

array([ 6.,  7.,  8.,  9., 10.])

In [ ]:
# Ejercicio 4
# Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2

In [30]:
arrayA = np.random.randint(1,100, 80)
arrayA

array([99,  7, 16, 90, 60,  2,  1, 48, 12, 69, 37, 32,  9, 99, 19, 48, 80,
        3, 20, 24, 54, 33, 24, 75, 72, 36, 38, 84, 99, 89, 99, 25, 93, 18,
       82, 66, 54, 35, 80, 61, 41, 33, 68, 33, 14, 21, 48, 20,  8,  7, 67,
       17, 33, 48, 76, 59, 86, 22, 30, 38, 51, 54,  8, 27, 27, 98, 21, 30,
       97, 28, 64, 97, 69, 61, 48, 19,  4, 35, 64, 49])

In [31]:
arrayB = np.random.randint(1,100, 80)
arrayB

array([17, 44, 92, 30, 93, 46,  6, 99, 37, 24, 93, 46, 53, 95, 99, 60, 97,
       63, 85, 32, 87, 33, 67, 18, 25, 95, 54, 58, 67, 46, 24, 32, 47, 86,
       23, 66, 27,  2, 90, 17, 33,  9, 43, 48, 39, 93, 42, 26, 99, 50, 25,
       24, 13, 60,  7, 57, 36, 45, 20, 65,  8, 16, 14, 76, 87, 15, 92, 98,
       66, 32, 87, 63, 86, 51, 25, 58, 63, 62, 22, 58])

In [39]:
# Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

arrayA = np.unique(arrayA)
arrayA

tamA = arrayA.size

In [45]:
arrayB = np.unique(arrayB)
arrayB

tamB = arrayB.size

In [46]:
# Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3

arrayC= np.setdiff1d(arrayA, arrayB)
arrayC

tamC = arrayC.size



In [47]:
# Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4

arrayD= np.setdiff1d(arrayB, arrayA)
arrayD

tamD = arrayD.size

In [48]:
# Identificad los elementos presentes en ambos arrays y asignarlos a una variable que se llame array5

arrayE = np.intersect1d(arrayA, arrayB)
arrayE

tamE= arrayE.size

In [ ]:
# ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [50]:
print(tamA) #unicos de A
print(tamB) #unicos de B
print(tamC) #valores de A que no están en B
print(tamD) #valores de B que no están en A
print(tamE) #valores comunes

53
54
22
23
31


In [55]:
# La suma de los valores de A que no están en B + los valores comunes, nos tiene que dar el tamaño de A

tamC + tamE == tamA

True

In [54]:
# La suma de los valores de B que no están en A + los valores comunes, nos tiene que dar el tamaño de B

tamD + tamE == tamB


True